"""
main.py  —  Life-cycle model engine.  Do not edit this file between runs.

To configure simulations, edit runs.py instead:
  • RUNS          — all simulation definitions
  • SELECTED_RUNS — which ones to execute right now

MODE = "two_group"  solves G1 + G2 + counterfactual → lifecycle + welfare
MODE = "benchmark"  solves G1 + G2 + G3 (no CF)     → benchmark overview
"""
import sys
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.interpolate import interp1d
import pandas as pd

# --- Path switcher (auto-detects server vs laptop, override with FORCE_ENV) --
FORCE_ENV = None   # set to "server" or "laptop" to force

_LAPTOP_ROOT     = Path(r"C:\Users\olsha\CBS - Copenhagen Business School\Patrick Natarajan Larsen - Thesis")
_LAPTOP_DATA     = _LAPTOP_ROOT / "05_Data" / "02_ Reference Data - PLEASE BE CAREFUL TO TOUCH"
_LAPTOP_CORE     = _LAPTOP_ROOT / "00_Model" / "core"
_LAPTOP_ANALYSIS = _LAPTOP_ROOT / "00_Model" / "analysis"
_LAPTOP_OUTPUT   = _LAPTOP_ROOT / "00_Model" / "output"

if FORCE_ENV == "server" or (FORCE_ENV is None and Path("/work/Home").exists()):
    DATA_DIR    = Path("/work/Home/01_thesis/data")
    _CORE       = "/work/Home/01_thesis/code/core"
    _ANALYSIS   = "/work/Home/01_thesis/code/analysis"
    SAVE_DIR    = Path("/work/Home/01_thesis/output")
    income_data = str(DATA_DIR / "properties stochastic income paths - 4-29-2026.csv")
    wir_data    = str(DATA_DIR / "WIR_at_25 - 5-4-2026.csv")
else:
    DATA_DIR    = _LAPTOP_DATA
    _CORE       = str(_LAPTOP_CORE)
    _ANALYSIS   = str(_LAPTOP_ANALYSIS)
    SAVE_DIR    = _LAPTOP_OUTPUT
    income_data = str(DATA_DIR / "properties stochastic income paths - 4-29-2026.csv")
    wir_data    = str(DATA_DIR / "WIR_at_25 - 5-4-2026.csv")
SAVE_DIR.mkdir(exist_ok=True)
# -----------------------------------------------------------------------------

# --- Spyder fix: clear cached modules ----------------------------------------
for _mod in ["make_income_growth", "grids_functions", "solve_endgrid",
             "simulate", "compute_value", "get_risk_premia", "plots",
             "compute_hc", "dashboard"]:
    sys.modules.pop(_mod, None)

for _p in [_CORE, _ANALYSIS]:
    if _p not in sys.path:
        sys.path.insert(0, _p)
# -----------------------------------------------------------------------------

from get_risk_premia     import calc_risk_premia, data as df_e_share
from grids_functions     import get_grids_and_functions
from solve_endgrid       import solve_endgrid
from simulate            import simulate
from compute_value       import compute_value
from make_income_growth  import create_the_G, masters_path, primary_path, econ_path
from plots               import plot_policy_functions, plot_lifecycle_profiles, \
                                plot_welfare_panel, plot_benchmark, plot_hc_wealth, \
                                plot_wealth_to_income, plot_income_equity_slide, \
                                resolve_color
from compute_hc          import compute_human_capital
from dashboard           import log_simulation
from runs                import RUNS, SELECTED_RUNS, DEFAULT_PLOTS

# ------------------------------------------------------------------
# SHARED parameters  (identical across all groups)
# ------------------------------------------------------------------
par_base = dict(
    start_age=25,
    mortality_table_start_age=0,
    T=70, T_ret=40,
    sigma=7, beta=0.96,
    rf=0.01, repl_rate=0.8,
    var_Eta=0.157**2,
    Nyy=9, NEta=5,
    ind_lifeRisky=1,
    Nxx=210, Nss=300, Nbb=300, Naa=330, Nalal=210,
    spacing=1.5,
    I=100_000,
)

# ------------------------------------------------------------------
# DATA  (loaded once at module level)
# ------------------------------------------------------------------
df     = pd.read_csv(income_data)
df_wir = pd.read_csv(wir_data).set_index("my_educ")

Var_P_MASTERS = df.loc[0, "V[P]_MASTERS"]
Var_V_MASTERS = df.loc[0, "V[V]_MASTERS"]
Var_P_PRIMARY = df.loc[0, "V[P]_PRIMARY"]
Var_V_PRIMARY = df.loc[0, "V[V]_PRIMARY"]
Var_P_ECON    = df.loc[0, "V[P]_ECON"]
Var_V_ECON    = df.loc[0, "V[V]_ECON"]

df_premia = calc_risk_premia(
    var_equity = par_base["var_Eta"],
    sigma      = par_base["sigma"],
    b_1        = 1,
    df_e_share = df_e_share,
)
# df_premia columns: my_educ | risk_premium_avg | risk_premium_primary
#                             | risk_premium_master | risk_premium_econ
# df_premia rows (my_educ):  "econ" | "master" | "primary"

# ------------------------------------------------------------------
# MODULE-LEVEL LOOKUPS AND HELPERS
# ------------------------------------------------------------------

# Variance lookups (permanent and transitory independently)
_VAR_N_TABLE = {"MASTERS": Var_P_MASTERS, "PRIMARY": Var_P_PRIMARY, "ECON": Var_P_ECON}
_VAR_V_TABLE = {"MASTERS": Var_V_MASTERS, "PRIMARY": Var_V_PRIMARY, "ECON": Var_V_ECON}

# Income path lookup — keys must match entries in RUNS dicts
PATHS = {
    "masters": masters_path,
    "primary": primary_path,
    "econ":    econ_path,
}

def _income_key(path):
    """Reverse-lookup: income path array → path name ("econ" / "masters" / "primary")."""
    return next((k for k, v in PATHS.items() if v == path), "econ")

_EDU_NAME    = {"econ": "Econ", "master": "Master's", "primary": "Primary"}
_PARENT_NAME = {"econ": "Econ parents", "master": "Master's parents",
                "primary": "Primary parents", "avg": "Avg. parents",
                "median": "Median parents"}
_REPL_RATE   = {"econ": 0.892, "master": 0.893, "primary": 0.914}

def _resolve_repl(val):
    """Accept a label string ("econ"/"master"/"primary") or a raw number."""
    if isinstance(val, str):
        return _REPL_RATE[val]
    return float(val)

def _auto_label(tau_educ, tau_parent):
    return f"{_EDU_NAME.get(tau_educ, tau_educ)} w. {_PARENT_NAME.get(tau_parent, tau_parent)}"

def _lookup_a0(tau_educ, tau_parent):
    """Look up starting normalised assets from the WIR-at-25 table."""
    col = f"parent_{tau_parent}"
    return float(df_wir.loc[tau_educ, col])

# ══════════════════════════════════════════════════════════════════════════════
#  Simulations are defined in runs.py — edit that file, not this one.
# ══════════════════════════════════════════════════════════════════════════════


# ------------------------------------------------------------------
# Helper: build a group parameter dict from cfg values
# ------------------------------------------------------------------
def _build_par(var_n_key, var_v_key, repl, tau_educ, tau_parent, a0=0.0):
    var_N = _VAR_N_TABLE[var_n_key]
    var_V = _VAR_V_TABLE[var_v_key]
    tau = df_premia.loc[
        df_premia["my_educ"] == tau_educ,
        f"risk_premium_{tau_parent}"
    ].values[0]
    return {**par_base, "var_N": var_N, "var_V": var_V,
            "tau": tau, "repl_rate": repl, "a0": a0}


# ------------------------------------------------------------------
# Helper: unpack simulation output into lifecycle moment arrays
# ------------------------------------------------------------------
def _lifecycle_moments(out, T):
    _, norm_a, sim_alpha, X, A, Y, _, _, _, _ = out
    C_arr = X - A
    mean_Y = Y.mean(axis=0);     std_Y = Y.std(axis=0)
    mean_A = A.mean(axis=0);     std_A = A.std(axis=0)
    mean_C = C_arr.mean(axis=0); std_C = C_arr.std(axis=0)
    mean_alpha = np.full(T, np.nan); std_alpha = np.full(T, np.nan)
    for t in range(T):
        mask = norm_a[:, t] > 0
        if mask.any():
            mean_alpha[t] = sim_alpha[mask, t].mean()
            std_alpha[t]  = sim_alpha[mask, t].std()
    return (Y, A, norm_a, sim_alpha,
            mean_Y, std_Y, mean_A, std_A,
            mean_C, std_C, mean_alpha, std_alpha)


def main(cfg):
    """Run one simulation defined by cfg and save all outputs."""

    name     = cfg.get("name", "unnamed")
    tags     = cfg.get("tags", [])
    MODE     = cfg.get("mode", "two_group")
    plots_cfg = {**DEFAULT_PLOTS, **cfg.get("plots", {})}

    print(f"\n{'═'*70}")
    print(f"  RUN: {name}   [{', '.join(tags)}]   mode={MODE}")
    print(f"{'═'*70}")

    # Output sub-folder for this run
    run_dir = SAVE_DIR / name
    run_dir.mkdir(exist_ok=True)

    # --- Unpack G1 ---
    income_g1    = cfg["income_g1"]
    INCOME_PATH_G1 = PATHS[income_g1]
    VAR_N_G1     = cfg["var_n_g1"]
    VAR_V_G1     = cfg["var_v_g1"]
    TAU_EDUC_G1  = cfg["tau_educ_g1"]
    TAU_PARENT_G1 = cfg["tau_parent_g1"]
    A0_EDUC_G1   = cfg["a0_educ_g1"]
    A0_PARENT_G1 = cfg["a0_parent_g1"]
    REPL_G1      = _resolve_repl(cfg["repl_g1"]) if "repl_g1" in cfg else _REPL_RATE[cfg.get("repl_educ_g1", TAU_EDUC_G1)]

    # --- Unpack G2 ---
    income_g2    = cfg["income_g2"]
    INCOME_PATH_G2 = PATHS[income_g2]
    VAR_N_G2     = cfg["var_n_g2"]
    VAR_V_G2     = cfg["var_v_g2"]
    TAU_EDUC_G2  = cfg["tau_educ_g2"]
    TAU_PARENT_G2 = cfg["tau_parent_g2"]
    A0_EDUC_G2   = cfg["a0_educ_g2"]
    A0_PARENT_G2 = cfg["a0_parent_g2"]
    REPL_G2      = _resolve_repl(cfg["repl_g2"]) if "repl_g2" in cfg else _REPL_RATE[cfg.get("repl_educ_g2", TAU_EDUC_G2)]

    # --- Auto-derive labels, colors, assets ---
    color_g1 = resolve_color(income_g1)
    color_g2 = resolve_color(income_g2)
    LABEL_G1 = _auto_label(TAU_EDUC_G1, TAU_PARENT_G1)
    LABEL_G2 = _auto_label(TAU_EDUC_G2, TAU_PARENT_G2)
    A0_G1    = _lookup_a0(A0_EDUC_G1, A0_PARENT_G1)
    A0_G2    = _lookup_a0(A0_EDUC_G2, A0_PARENT_G2)

    # --- Unpack G3 (benchmark only) ---
    if MODE == "benchmark":
        income_g3    = cfg["income_g3"]
        INCOME_PATH_G3 = PATHS[income_g3]
        VAR_N_G3     = cfg["var_n_g3"]
        VAR_V_G3     = cfg["var_v_g3"]
        TAU_EDUC_G3  = cfg["tau_educ_g3"]
        TAU_PARENT_G3 = cfg["tau_parent_g3"]
        A0_EDUC_G3   = cfg["a0_educ_g3"]
        A0_PARENT_G3 = cfg["a0_parent_g3"]
        REPL_G3      = _resolve_repl(cfg["repl_g3"]) if "repl_g3" in cfg else _REPL_RATE[cfg.get("repl_educ_g3", TAU_EDUC_G3)]
        color_g3     = resolve_color(income_g3)
        LABEL_G3     = _auto_label(TAU_EDUC_G3, TAU_PARENT_G3)
        A0_G3        = _lookup_a0(A0_EDUC_G3, A0_PARENT_G3)

    T         = par_base["T"]
    T_ret     = par_base["T_ret"]
    start_age = par_base["start_age"]
    ret_age   = start_age + T_ret
    n_groups  = 3 if MODE == "benchmark" else 2
    I_each    = par_base["I"] // n_groups

    # Build group parameter dicts
    PAR_G1    = _build_par(VAR_N_G1, VAR_V_G1, REPL_G1, TAU_EDUC_G1, TAU_PARENT_G1, A0_G1)
    PAR_G2    = _build_par(VAR_N_G2, VAR_V_G2, REPL_G2, TAU_EDUC_G2, TAU_PARENT_G2, A0_G2)
    PAR_G2_cf = {**PAR_G2, "tau": PAR_G1["tau"]}

    # ==================================================================
    # GROUP 1
    # ==================================================================
    print(f"\n--- G1 | income={income_g1} | var_N={VAR_N_G1} var_V={VAR_V_G1}"
          f" | repl={REPL_G1} | tau({TAU_EDUC_G1},{TAU_PARENT_G1})={PAR_G1['tau']:.4f} ---")

    G1 = create_the_G(INCOME_PATH_G1, T_ret=T_ret, start_age=start_age)
    spa1, par1, _, f_MU1, f_MUinv1 = get_grids_and_functions(PAR_G1, G_work=G1)
    x_end1, c_end1, a_end1, alpha_end1 = solve_endgrid(par1, spa1, f_MU1, f_MUinv1)
    out1 = simulate(35465465, {**par1, "I": I_each}, spa1,
                    a_func=a_end1, alpha_func=alpha_end1,
                    s_func=None, b_func=None, xgrid=x_end1, method="endgrid")

    # ==================================================================
    # GROUP 2
    # ==================================================================
    print(f"\n--- G2 | income={income_g2} | var_N={VAR_N_G2} var_V={VAR_V_G2}"
          f" | repl={REPL_G2} | tau({TAU_EDUC_G2},{TAU_PARENT_G2})={PAR_G2['tau']:.4f} ---")

    G2 = create_the_G(INCOME_PATH_G2, T_ret=T_ret, start_age=start_age)
    spa2, par2, _, f_MU2, f_MUinv2 = get_grids_and_functions(PAR_G2, G_work=G2)
    x_end2, c_end2, a_end2, alpha_end2 = solve_endgrid(par2, spa2, f_MU2, f_MUinv2)
    out2 = simulate(35465465, {**par2, "I": I_each}, spa2,
                    a_func=a_end2, alpha_func=alpha_end2,
                    s_func=None, b_func=None, xgrid=x_end2, method="endgrid")

    # ==================================================================
    # GROUP 3  (benchmark only)
    # ==================================================================
    if MODE == "benchmark":
        PAR_G3 = _build_par(VAR_N_G3, VAR_V_G3, REPL_G3, TAU_EDUC_G3, TAU_PARENT_G3, A0_G3)
        print(f"\n--- G3 | income={income_g3} | var_N={VAR_N_G3} var_V={VAR_V_G3}"
              f" | repl={REPL_G3} | tau({TAU_EDUC_G3},{TAU_PARENT_G3})={PAR_G3['tau']:.4f} ---")

        G3 = create_the_G(INCOME_PATH_G3, T_ret=T_ret, start_age=start_age)
        spa3, par3, _, f_MU3, f_MUinv3 = get_grids_and_functions(PAR_G3, G_work=G3)
        x_end3, c_end3, a_end3, alpha_end3 = solve_endgrid(par3, spa3, f_MU3, f_MUinv3)
        out3 = simulate(35465467, {**par3, "I": I_each}, spa3,
                        a_func=a_end3, alpha_func=alpha_end3,
                        s_func=None, b_func=None, xgrid=x_end3, method="endgrid")

    # ==================================================================
    # COUNTERFACTUAL  (two_group only — G2 income/risk, G1 tau)
    # ==================================================================
    if MODE == "two_group":
        print(f"\n--- G2-cf | tau swapped to G1: {PAR_G2_cf['tau']:.4f} ---")
        G2_cf = create_the_G(INCOME_PATH_G2, T_ret=T_ret, start_age=start_age)
        spa2_cf, par2_cf, _, f_MU2_cf, f_MUinv2_cf = get_grids_and_functions(PAR_G2_cf, G_work=G2_cf)
        x_end2_cf, c_end2_cf, a_end2_cf, alpha_end2_cf = solve_endgrid(
            par2_cf, spa2_cf, f_MU2_cf, f_MUinv2_cf)
        out2_cf = simulate(35465465, {**par2_cf, "I": I_each}, spa2_cf,
                           a_func=a_end2_cf, alpha_func=alpha_end2_cf,
                           s_func=None, b_func=None, xgrid=x_end2_cf, method="endgrid")

    # ==================================================================
    # UNPACK MOMENTS
    # ==================================================================
    age = np.arange(start_age, start_age + T)

    (Y1, A1, norm_a1, sim_alpha1,
     mean_Y1, std_Y1, mean_A1, std_A1,
     mean_C1, std_C1, mean_alpha1, std_alpha1) = _lifecycle_moments(out1, T)

    (Y2, A2, norm_a2, sim_alpha2,
     mean_Y2, std_Y2, mean_A2, std_A2,
     mean_C2, std_C2, mean_alpha2, std_alpha2) = _lifecycle_moments(out2, T)

    if MODE == "benchmark":
        (Y3, A3, norm_a3, sim_alpha3,
         mean_Y3, std_Y3, mean_A3, std_A3,
         mean_C3, std_C3, mean_alpha3, std_alpha3) = _lifecycle_moments(out3, T)

    # ==================================================================
    # PLOTS
    # ==================================================================
    if MODE == "benchmark":
        plot_benchmark(age,
                       mean_Y1, mean_Y2, mean_Y3,
                       mean_C1, mean_C2, mean_C3,
                       mean_A1, mean_A2, mean_A3,
                       mean_alpha1, mean_alpha2, mean_alpha3,
                       start_age, T, ret_age, run_dir,
                       label_g1=LABEL_G1, label_g2=LABEL_G2, label_g3=LABEL_G3,
                       color_g1=color_g1, color_g2=color_g2, color_g3=color_g3)

        # Policy functions: G1 (Econ) only — single-group mode
        if plots_cfg["policy_functions"]:
            plot_policy_functions(x_end1, a_end1, alpha_end1,
                                  None, None, None,
                                  start_age, run_dir,
                                  label_g1=LABEL_G1, label_g2=None,
                                  color_g1=color_g1, color_g2=None)
    else:
        if plots_cfg["policy_functions"]:
            plot_policy_functions(x_end1, a_end1, alpha_end1,
                                  x_end2, a_end2, alpha_end2,
                                  start_age, run_dir,
                                  label_g1=LABEL_G1, label_g2=LABEL_G2,
                                  color_g1=color_g1, color_g2=color_g2)

        if plots_cfg["lifecycle_profiles"]:
            plot_lifecycle_profiles(age,
                                    mean_Y1, std_Y1, mean_Y2, std_Y2,
                                    mean_C1, std_C1, mean_C2, std_C2,
                                    mean_A1, std_A1, mean_A2, std_A2,
                                    mean_alpha1, std_alpha1, mean_alpha2, std_alpha2,
                                    start_age, T, ret_age, run_dir,
                                    label_g1=LABEL_G1, label_g2=LABEL_G2,
                                    color_g1=color_g1, color_g2=color_g2)

        if plots_cfg["human_capital_wealth"]:
            mean_HC1 = compute_human_capital(Y1, spa1["pS"], par1["rf"])
            mean_HC2 = compute_human_capital(Y2, spa2["pS"], par2["rf"])
            plot_hc_wealth(age, mean_HC1, mean_HC2, mean_A1, mean_A2,
                           start_age, T, ret_age, run_dir,
                           label_g1=LABEL_G1, label_g2=LABEL_G2,
                           color_g1=color_g1, color_g2=color_g2)

        if plots_cfg["wealth_to_income"]:
            plot_wealth_to_income(age, mean_A1, mean_Y1, mean_A2, mean_Y2,
                                  start_age, T, ret_age, run_dir,
                                  label_g1=LABEL_G1, label_g2=LABEL_G2,
                                  color_g1=color_g1, color_g2=color_g2)

        if plots_cfg["income_equity_slide"]:
            plot_income_equity_slide(age,
                                     mean_Y1, std_Y1, mean_Y2, std_Y2,
                                     mean_alpha1, std_alpha1, mean_alpha2, std_alpha2,
                                     start_age, T, ret_age, run_dir,
                                     label_g1=LABEL_G1, label_g2=LABEL_G2,
                                     color_g1=color_g1, color_g2=color_g2)

    # ==================================================================
    # WELFARE  (two_group only)
    # ==================================================================
    CE_pct = None
    if MODE == "two_group":
        V_base = compute_value(par2,    spa2,    x_end2,    c_end2,    alpha_end2)
        V_cf   = compute_value(par2_cf, spa2_cf, x_end2_cf, c_end2_cf, alpha_end2_cf)

        x0 = 1.0
        iV_base = interp1d(x_end2[:, 0],    V_base[:, 0], kind="linear",
                           bounds_error=False, fill_value=(V_base[0, 0], 0.0))
        iV_cf   = interp1d(x_end2_cf[:, 0], V_cf[:, 0],   kind="linear",
                           bounds_error=False, fill_value=(V_cf[0, 0],   0.0))

        sigma  = par_base["sigma"]
        lam    = (float(iV_cf(x0)) / float(iV_base(x0))) ** (1.0 / (1.0 - sigma))
        CE_pct = (lam - 1) * 100

        # CE in absolute DKK (mean_C2 is kDKK per year; × 1000 → DKK)
        ce_dkk_annual   = np.nanmean(mean_C2) * (CE_pct / 100) * 1_000
        ce_dkk_lifetime = np.nansum(mean_C2)  * (CE_pct / 100) * 1_000

        print(f"\n  CE gain = {CE_pct:+.2f}%")
        print(f"  CE (annual avg)  = {ce_dkk_annual:>10,.0f} DKK/year")
        print(f"  CE (lifetime sum)= {ce_dkk_lifetime:>10,.0f} DKK total")

        t_ret  = T_ret - 1
        wir1   = A1[:, t_ret] / Y1[:, t_ret]
        wir2   = A2[:, t_ret] / Y2[:, t_ret]
        m1_ret = norm_a1[:, t_ret] > 0
        m2_ret = norm_a2[:, t_ret] > 0

        (_, _, _, _, A2_cf, Y2_cf, _, _, _, _) = out2_cf
        wir2_cf = A2_cf[:, t_ret] / Y2_cf[:, t_ret]

        wir1_mean   = wir1.mean();          wir2_mean   = wir2.mean()
        wir1_med    = np.median(wir1);      wir2_med    = np.median(wir2)
        wir2_cf_mean = wir2_cf.mean();      wir2_cf_med = np.median(wir2_cf)
        print(f"  WIR (mean)    G1: {wir1_mean:.2f}  |  G2: {wir2_mean:.2f}"
              f"  |  ratio G1/G2: {wir1_mean / wir2_mean:.3f}")
        print(f"  WIR (median)  G1: {wir1_med:.2f}  |  G2: {wir2_med:.2f}"
              f"  |  ratio G1/G2: {wir1_med / wir2_med:.3f}")
        print(f"  WIR-cf (mean) G2+G1τ: {wir2_cf_mean:.2f}  |  ratio cf/G2: {wir2_cf_mean / wir2_mean:.3f}")
        print(f"  α             G1: {sim_alpha1[m1_ret, t_ret].mean():.3f}"
              f"  |  G2: {sim_alpha2[m2_ret, t_ret].mean():.3f}")

        if plots_cfg["welfare_panel"]:
            plot_welfare_panel(CE_pct, wir1, wir2, wir2_cf,
                               PAR_G1["tau"], PAR_G2["tau"],
                               start_age, t_ret, run_dir,
                               label_g1=LABEL_G1, label_g2=LABEL_G2,
                               color_g1=color_g1, color_g2=color_g2)

    # ==================================================================
    # DASHBOARD LOG
    # ==================================================================
    _figs_two = [run_dir / "policy_functions.png",
                 run_dir / "lifecycle_profiles.png",
                 run_dir / "wealth_to_income.png",
                 run_dir / "hc_wealth.png",
                 run_dir / "consumption_equivalent.png"]
    _figs_bench = [run_dir / "benchmark_overview.png",
                   run_dir / "policy_functions.png"]

    _groups = [
        {"label": LABEL_G1, "income": income_g1,
         "var_n_key": VAR_N_G1, "var_v_key": VAR_V_G1, "repl_rate": REPL_G1,
         "tau_educ": TAU_EDUC_G1, "tau_parent": TAU_PARENT_G1,
         "a0_educ": A0_EDUC_G1, "a0_parent": A0_PARENT_G1, "a0_val": A0_G1},
        {"label": LABEL_G2, "income": income_g2,
         "var_n_key": VAR_N_G2, "var_v_key": VAR_V_G2, "repl_rate": REPL_G2,
         "tau_educ": TAU_EDUC_G2, "tau_parent": TAU_PARENT_G2,
         "a0_educ": A0_EDUC_G2, "a0_parent": A0_PARENT_G2, "a0_val": A0_G2},
    ]
    if MODE == "benchmark":
        _groups.append(
            {"label": LABEL_G3, "income": income_g3,
             "var_n_key": VAR_N_G3, "var_v_key": VAR_V_G3, "repl_rate": REPL_G3,
             "tau_educ": TAU_EDUC_G3, "tau_parent": TAU_PARENT_G3,
             "a0_educ": A0_EDUC_G3, "a0_parent": A0_PARENT_G3, "a0_val": A0_G3}
        )

    _params = {
        "shared": {"sigma": par_base["sigma"],
                   "beta":  par_base["beta"],
                   "rf":    par_base["rf"]},
        "groups": _groups,
    }
    if CE_pct is not None:
        _params["ce_pct"]          = round(CE_pct, 4)
        _params["ce_dkk_annual"]   = round(ce_dkk_annual, 0)
        _params["ce_dkk_lifetime"] = round(ce_dkk_lifetime, 0)

    log_simulation(
        name     = name,
        tags     = tags,
        figures  = _figs_two if MODE == "two_group" else _figs_bench,
        save_dir = SAVE_DIR,
        params   = _params,
    )


if __name__ == "__main__":
    to_run = (
        [r for r in RUNS if r["name"] in SELECTED_RUNS]
        if SELECTED_RUNS is not None
        else RUNS
    )
    for cfg in to_run:
        main(cfg)
